version: '3'

services:
  neo4j-db:
    image: neo4j:latest
    restart: always
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/example123
    volumes:
      - ./data:/data